### ISSUE TITLE
/sign always returns authentication failed

### ISSUE THREAD

**Issue by alexlouden** [ryansmith3136/l2met#104]
Hey guys,

The setup script is returning auth failed. Any ideas?

```
...
L2met health check passed.
Drain URL: https://Authentication failed.@myl2met.herokuapp.com/logs"
```

The secrets environmental variable is set:

```
$ heroku config:get SECRETS
pZewe3Nd...d9xywqaBA=
$ echo $secret
pZewe3Nd...d9xywqaBA=

$ curl -s "https://myl2met.herokuapp.com/sign" --data "myemail:myapikey" -u "$secret:"
Authentication failed.
```

Any ideas?

**Comment by ryansmith3136** [comment]
Sorry for the troubles here, MASTER has been under heavy development recently. I am hoping to make a stable release soon.

As for you specific problem, try this:

``` bash
$ curl -s "https://myl2met.herokuapp.com/sign" --data "myemail:myapikey" -u "$secret"
```

**Comment by ryansmith3136** [comment]
@alexlouden There was a bug introduced recently. I have applied a fix. Feel free to re-open if you are still having troubles.
