### ISSUE TITLE
Lots of "error=Unable to decrypt" in l2met logs

### ISSUE THREAD

**Issue by jamischarles** [ryansmith3136/l2met#108]
`app[web.1]: error=Unable to decrypt.`

Seeing lots of these in my l2met logs. I'm assuming this is an issue with the librato decryption. Couldn't find anything else in your docs though.

Thoughts?

**Comment by ryansmith3136** [comment]
Interesting. Let me try and reproduce. Is l2met actually working for you? Are you getting data into Librato? How many apps are draining into l2met? Were the drain urls are signed using the same `$SECRET` ?

**Comment by jamischarles** [comment]
Got it.

I was draining 5 apps into l2met.

One of them was draining twice (one with the wrong secret).

Fixing that also made my 4xx errors drop to zero.

I'll add this to FAQ. Thanks.
