### ISSUE TITLE
Q: How should cloudwatch data be handled?

### ISSUE THREAD

**Issue by mikehale** [ryansmith3136/l2met#11]
Cloudwatch data has a maximum resolution of 60 seconds. Internally more data is stored. Take for example ELB latency:

``` ruby
[
        {
                  :metric => "mhale.elb000007.latency.minimum",
                   :value => 4.0e-06,
            :measure_time => 2012-12-05 17:14:00 UTC
        },
        {
                  :metric => "mhale.elb000007.latency.maximum",
                   :value => 5.7e-05,
            :measure_time => 2012-12-05 17:14:00 UTC
        },
        {
                  :metric => "mhale.elb000007.latency.sum",
                   :value => 0.004026,
            :measure_time => 2012-12-05 17:14:00 UTC
        },
        {
                  :metric => "mhale.elb000007.latency.average",
                   :value => 8.182926829268293e-06,
            :measure_time => 2012-12-05 17:14:00 UTC
        },
        {
                  :metric => "mhale.elb000007.latency.sample_count",
                   :value => 492.0,
            :measure_time => 2012-12-05 17:14:00 UTC
        }
    ]
```

It seems un-necessary to have l2met calculate min, max, perc99, etc on data that is already at a 60 second resolution, because all of the metrics will be identical. Perhaps l2met could have a way to signal that data should just be passed through? Maybe it could rely on a `period=60` attribute?

Additionally I'm wondering if it makes sense to submit this data to librato using the [multi-sample format](http://dev.librato.com/v1/post/metrics). Does submitting multi-sample formatted data buy us anything here? It seems like it should help to minimize the data loss from cloudwatch, but I'm not sure what that looks like in librato.

/cc @josephruscio

**Comment by josephruscio** [comment]
@mikehale submitting the data in the multi-sample format would reduce your Librato bill. We consider a single multi-sample of <sum, count, min, max> a single measurement for billing purposes. So in this case you'd cut your bill for this data by a factor of 5.

The current (albeit temporary) downside is that we don't expose min/max/count through the UI yet. All of the multi-sample fields are available through the API, and you can access the sum or average through the UI. That's actually something we're going to add in the very near future however, so I think it would still make sense to go with the mult-sample format? /cc @mheffner

**Comment by mikehale** [comment]
@josephruscio Thanks. I'm not a stats expert, but it seems like this allows one to represent a large amount of data points with a few numbers. So it is lossy, but not as lossy as a straight average. Is that correct? I'm curious about what that will look like in the UI. Does having the multi-sample data allow the graphs to be drawn more in line with the full resolution data, while still only having a few numbers to pull from?

**Comment by mheffner** [comment]
@mikehale At the lowest (raw) resolution there would be no loss at all. Using the complex gauges you would essentially be submitting the values above (mod 'avg' since that should equal sum/sample_count) in a single gauge measurement. Like Joe said, at the moment you would not be able to plot min or max values across points using the UI, but we do plan to support that soon. The min/max data is still accessible via the API, you just can't graph it.

On a rollup we'll track the total sum and sample-count for all points in the rollup sample (simple summation). We also track the greatest max and least min over a rollup period. There is some loss potential if you are concerned about tracking average min or average max across a rollup period.
