### ISSUE TITLE
Allow multiple sources to be specified for metrics

### ISSUE THREAD

**Issue by BRMatt** [ryansmith3136/l2met#113]
The usecase would be aggregating data for the entire application, but at the same time recording data at a more granular level. An example of this would be recording the time spent in the db/views/cache at a controller+action level, and also have an application wide overview to see the worst performance across all parts of the app.

We could either use multiple source statements per log line (i.e. `source=foo source=bar`), or supply comma separated values to one source statement, though this might get a little unwieldy:

```
source=production,admin_settings_integrate_service.create
```

Thoughts?

**Comment by ryansmith3136** [comment]
You can provide metrics with a specific source and then aggregate the data by manipulating the source in Librato's UI. Do you find this technique unsatisfactory for solving your problem? http://support.metrics.librato.com/knowledgebase/articles/96653-instrument-and-dashboard-templates-dynamic-source

**Comment by BRMatt** [comment]
It might do, but last time I tried the aggregation with the multiple domains for router requests it seemed to display lines for each of the sources rather than a single aggregated value, though I might've been doing it wrong. I'll take a look when I get back from holiday and report back.

**Comment by BRMatt** [comment]
Tried this today, seems like librato's ui does exactly what we need.
