### ISSUE TITLE
Installation not working - no drain URL returned

### ISSUE THREAD

**Issue by summerville** [ryansmith3136/l2met#114]
Hi,

I've followed the instructions in the README several times but keep getting the same error when installing l2met. Heroku and Librato are setup. Here's what I'm seeing:

``` Bash
./scripts/setup: line 100: [: too many arguments
L2met health check failed. Run: heroku logs -t
Drain URL: https://<!DOCTYPE html>
    <html>
    <head>
        <title>Heroku | Welcome to your new app!</title>
        <style type='text/css'> 
      body {

```

Any ideas on what I'm doing wrong?

Thanks!

**Comment by ryansmith3136** [comment]
I played around with the setup myself to try and reproduce. I was able to. I think this is related to #105

**Comment by ryansmith3136** [comment]
I bet if you inspect the `SECRETS` variable you will notice a non url safe character.

``` bash
$ heroku config:get SECRETS
VMmlPyyq/zPG5m49yJIqgRVaJARiiEx539sHEElPwwg
```

In this example, you can simply replace `/` with any other alpha numeric character.

**Comment by ryansmith3136** [comment]
@summerville You may want to give the updated setup script a try.

**Comment by summerville** [comment]
Boom! That got it. Thanks a ton!
