### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by josephruscio** [ryansmith3136/l2met#117]
Upstream l2met (this repo) should run tests on Travis.org.

**Comment by ryansmith3136** [comment]
I am curious as to your motivation. What problem would this solve?

FIWI: I use drone.io for the build/CI service on l2met because it is simpler and faster than travis. Last time I used travis for l2met, it took almost 5 minutes to execute a build. On drone.io it takes ~5s.

**Comment by josephruscio** [comment]
I filed this because I thought master in our private fork was failing tests. It turns out that Travis apparently will run tests on branches without a .travis.yml file, and assume they are Ruby :-1:. I'm going to close this because the original motivation isn't valid.

That aside, it would provide a public/automated indicator of the validity of master. If (drone.io or any other CI provider) has some Github integration that would be fine too. Food for thought ;-).

**Comment by ryansmith3136** [comment]
@josephruscio Did you see the badge under the hacking/testing section of the README? 

https://github.com/ryandotsmith/l2met#running-tests

Maybe it would be better to place it at the top?

**Comment by josephruscio** [comment]
I did not see it and :+1: to placing it at the top. That seems to be the convention for important badges like CI or code quality.
