### ISSUE TITLE
Investigate Librato complex measurement support

### ISSUE THREAD

**Issue by josephruscio** [ryansmith3136/l2met#12]
Librato supports representing a multi-sample aggregate [as a single gauge measurement](http://dev.librato.com/v1/post/metrics) (scroll down to `Gauge Specific Parameters`). In theory you could submit the:
1. sample count
2. sample sum
3. sample min
4. sample max

as a single measurement instead of 5 separate metrics (we calculate the average as sum/count), and cut your billed usage by a factor of 5? We need to add support for accessing the count/min/max through the UI, but I think we could coordinate doing that with an update here? /cc @freeformz

**Comment by ryansmith3136** [comment]
@josephruscio I am eager to take advantage of this feature. When do you expect the librato UI changes can be shipped?

**Comment by josephruscio** [comment]
I was literally just typing up a reference to this in #29 as this is some extremely low-hanging fruit to cut down the total number of measurements. I think we can have it out next week if you want to start coordinating how the switchover will work. /cc @dpiddy

**Comment by ryansmith3136** [comment]
Started WIP at #50.

Lets take the discussion there.
