### ISSUE TITLE
Set the period of a guage correctly.

### ISSUE THREAD

**Issue by freeformz** [ryansmith3136/l2met#13]
This is needed so a simple transform of x/p works correctly.

**Comment by ryansmith3136** [comment]
@freeformz Can you provide some more detail here?

**Comment by josephruscio** [comment]
@ryandotsmith if you set the period on a gauge, we can do several things:
1. Properly align data-points on stacked area graph
2. Enable display transforms like `x/p` that render a per-second rate correctly at any rollup level
3. Zero-fill missing data when aggregation is configured to `sum`
4. In the future, hopefully alert when data stop's showing up for N periods.

@freeformz fwiw, we're deep into building a _mass attribute editing_ feature that would let you set the period across all existing metrics that match a pattern e.g. `shh.*`.

**Comment by freeformz** [comment]
@ryandotsmith what @josephruscio said.

**Comment by ryansmith3136** [comment]
I was unable to find any mention of `period` here: http://dev.librato.com/v1/post/metrics

Is this feature not documented?

**Comment by freeformz** [comment]
See "Optional Parameters" here: http://dev.librato.com/v1/put/metrics/:name

From the link you provided:

NOTE: The optional parameters listed in the metrics PUT operation can be used with POST operations, but they will be ignored if the metric already exists. To update existing metrics, please use the PUT operation.

**Comment by bgentry** [comment]
Does this issue have any bearing on high-res 1sec charts from l2met?

**Comment by freeformz** [comment]
bump
