### ISSUE TITLE
support counters

### ISSUE THREAD

**Issue by freeformz** [ryansmith3136/l2met#14]
Most system metrics are counters and we need librato to graph the derivative.

**Comment by freeformz** [comment]
Alternative is to report the difference to librato from l2met.
Otherwise my app needs to calculate the difference between ticks and report those instead, this complicates things.
Either way someone needs to calculate it and I'd rather push that as far away from the metric reporting app as possible.

**Comment by freeformz** [comment]
After talking to @josephruscio it's best that l2met support counters for now and have librato handle the derivatives.

**Comment by josephruscio** [comment]
@freeformz correct. We're going to be adding support for graphite-style functions very soon, at which point you could just push the raw counter values up as a gauge, and then add a derivative to the metric attributes. But at this point in time to achieve a derivative, you need to push those up as counters. Note that this is how our collectd backend deals with all the values in `/proc` as well.

**Comment by freeformz** [comment]
Closing because this was handled in #69
