### ISSUE TITLE
YALF

### ISSUE THREAD

**Issue by ryansmith3136** [ryansmith3136/l2met#22]
Yet Another Log Format.

**The Problem**

It is impossible to have multiple measurements in one log line. There are certain high volume systems for which it is not feasible to have one log line per measurement. Moving from 1x to 10x the number of logs on a system that does ~50,000 things per second is unreasonable.

**A Solution**

I would like to deprecate the `measure=x val=y` format in favor of a more loosely defined format. The format would roughly match the following regex: 

`([a-zA-Z0-9\_\-\.]+)=([0-9\.\-\_\.]+)` 

This has the added benefit of working with the heroku router.

```
at=info method=POST path=/logs host=l2met-vis.herokuapp.com fwd="54.242.205.127" dyno=web.1 queue=0 wait=2ms connect=8ms service=13ms status=200 bytes=0
```

**Comment by ryansmith3136** [comment]
This change may increase the number of measurements that are taken. This will impact the amount of data l2met has to process in addition to the increase of metrics sent to librato.

**Comment by josephruscio** [comment]
@ryandotsmith why would it increase the number of measurements? You mean from a behavioral perspective people will submit more measurements because it's easier?

**Comment by ryansmith3136** [comment]
The current format forces you to be explicit about what you want to measure. The new format will pick up a lot more data in a typical app stream. For example, consider a heroku app that adds a drain, in addition to getting measurements that your code is logging, you will also get the Heroku router measurements. I think this is great because you know have visibility into your router but at the cost of managing more data.

**Comment by ryansmith3136** [comment]
related: #27
