### ISSUE TITLE
Extra metrics sent to librato

### ISSUE THREAD

**Issue by mikehale** [ryansmith3136/l2met#24]
With a new drain and sending `measure= source=` I'm seeing min, max, etc. I only expected to have .count since I did not specify `val=`.

**Comment by ryansmith3136** [comment]
@mikehale will this continue to be a problem even in light of #50 ?

**Comment by mikehale** [comment]
Actually I think think this request was around an [old log convention (counters vs lists)](https://github.com/ryandotsmith/l2met/blob/309d8fbd55d9058ae612cb72a11c7a2c444bd72d/readme.md#counters). Based on the readme I was expecting a single metric to be produced, but it appears that l2met has changed in behavior here so this issue does not apply anymore.
