### ISSUE TITLE
Track production branch

### ISSUE THREAD

**Issue by bgentry** [ryansmith3136/l2met#38]
It's very frustrating as a user of l2met to not have the Readme actually reflect the current deployed feature-set. It's also frustrating when the build on master is broken or just not functional. Please consider either:

a. doing all development in branches / PRs
b. keeping a branch that reflects what's deployed to production

**Comment by ryansmith3136** [comment]
This is a really good point. Perhaps we need a development branch. Also, we could probably get better at doing releases. Maybe keeping a version number and using tags could help keep things organized.

**Comment by ryansmith3136** [comment]
In addition to keeping feature/development branches, I have also started to tag releases. E.g. https://github.com/ryandotsmith/l2met/tree/v0.1
