### ISSUE TITLE
Hight latency Librato requests create backlog

### ISSUE THREAD

**Issue by ryansmith3136** [ryansmith3136/l2met#4]
In last night's aws outage, l2met was having troubles keeping up with measurement postings. I am not sure what the correct solution is, but this is definitely a problem.

**Comment by josephruscio** [comment]
@ryandotsmith can you (or have you already) add a custom User-Agent on the requests made by l2met? We recommend that new collectors add a unique User-Agent header so that we have the option of collecting statistics (e.g. latency) for a given collector e.g.

```
l2met/0.0.1
```

**Comment by josephruscio** [comment]
Also did you perceive an increase in latency to requests made to @librato during the outage period? Or does this refer to the latencies typically seen to @librato exacerbating the problem? /cc @mheffner

**Comment by ryansmith3136** [comment]
Not a real problem.
