### ISSUE TITLE
http 500 when visiting www.l2met.net

### ISSUE THREAD

**Issue by gorsuch** [ryansmith3136/l2met#5]
http://cl.ly/image/0H0p3p0G3s20

Howdy!  Can you patch things up for me!

**Comment by ryansmith3136** [comment]
@gorsuch OK. I fixed the problem that was causing the 500s. How I have a problem with Sinatra::GoogleAuth. Let me dig in on this one. Nothing has changed.... Not sure what to do.

**Comment by ryansmith3136** [comment]
After looking in the logs, I saw the following message:

```
ERROR -- omniauth: (google) Authentication failure! connection_failed encountered.
```

I will go to the googles to figure out what is going on here. @gorsuch have you seen this before?
