### ISSUE TITLE
Handle pre-aggregated metrics

### ISSUE THREAD

**Issue by mikehale** [ryansmith3136/l2met#51]
In the case of AWS cloudwatch, data has already been collected and aggregated over a 60 second period. Cloudwatch provides access to min, max, avg, sum, and sample count values for this 60 second period. I'd like a way to route these raw data points through l2met without any additional aggregation happening on them. For example, sending the following event to l2met:

``` ruby
$stdout.puts("measure.elb.latency.min=0.000s measure.elb.latency.max=1.660s measure.elb.latency.sum=2715.167s measure.elb.latency.sample_count=67448s source=elb018876.us-east-1d measure.time=1366295100")
```

Would produce the following metrics:
- measure.elb.latency.min
- measure.elb.latency.max
- measure.elb.latency.sum
- measure.elb.latency.sample_count

The metrics would all have a source of `elb018876.us-east-1d` and would be [timestamped](https://github.com/ryandotsmith/l2met/issues/15) at the value of `measure.time` (1366295100).

I'm not tied to the exact formatting of the above, I mainly wanted a concrete example to show the desired result of passing pre-aggregated metrics through l2met. This example seeks to use l2met not as an aggregation tool, but simply as a way to route structured log data to a metric storage service in a way that does not require the originating application to be tightly coupled to the metric storage and visualization service. i.e `STDOUT` plus drains.

**Comment by mikehale** [comment]
Having this in place would allow me to eliminate [m2met](https://github.com/heroku/m2met).

**Comment by ryansmith3136** [comment]
@mikehale I think the proposed changes in #69 would handle this case. Correct me if I am wrong.

**Comment by mikehale** [comment]
@ryandotsmith agree.
