### ISSUE TITLE
l2met.tar.gz is a TAR (not TAR GZ)

### ISSUE THREAD

**Issue by ryanbrainard** [ryansmith3136/l2met#58]
The readme says to do this:

```
curl https://s3-us-west-2.amazonaws.com/l2met/v1.0/linux/amd64/l2met.tar.gz | tar xvz
```

but results in:

   gzip: stdin: not in gzip format

The file is a TAR, but not TAR GZ. This works (without `z`):

```
curl https://s3-us-west-2.amazonaws.com/l2met/v1.0/linux/amd64/l2met.tar.gz | tar xv
```

Of course actually having the file gzipped would work too :)

**Comment by ryansmith3136** [comment]
Good call. I just updated the s3 bucket with the tared and zipped version.
