### ISSUE TITLE
Heroku runtime metrics have UUIDs in the source

### ISSUE THREAD

**Issue by ryansmith3136** [ryansmith3136/l2met#60]
This is a problem as it creates new librato metric streams.

**Comment by mheffner** [comment]
Example of current source names:

```
heroku.123456.web.1.b046d162-ca64-4b2a-8f49-bcb955a50935
heroku.456890.web.4.e1e15569-ca42-47bc-bd46-0e8d9fb51b32
heroku.456890.run.8260.468c493b-cd74-41e9-a92b-878706fa1b33
```

Where 123456 and 456890 are the Heroku account ID and GUID is regenerated after each deploy

Ideally these would be reported as:

```
 web.1
 web.4
 run.8260
```

**Comment by ryansmith3136** [comment]
No longer an issue now that heroku's runtime metrics support l2met's latest format. https://devcenter.heroku.com/changelog-items/315
