### ISSUE TITLE
Publish internal metrics to outlet

### ISSUE THREAD

**Issue by ryansmith3136** [ryansmith3136/l2met#62]
While it is tempting to just use l2met to monitor l2met, it may be simpler if l2met kept a set of internal metrics and pushed them through the outlet.

**Comment by ryansmith3136** [comment]
Made a first pass at this issue. If you set `OUTLET_USER` and `OUTLET_PASS` then l2met will publish an internal metric to librato user the aforementioned credentials. Currently there is only one metric being published. I setup a timer around the function that makes an http request into metrics. This will report the rate at which we are receiving http requests and the time it takes to process those requests.

**Comment by ryansmith3136** [comment]
cc: @josephruscio

**Comment by ryansmith3136** [comment]
Here is the [commit](https://github.com/ryandotsmith/l2met/commit/7759b6f2a4ab35546711bd232de03be8e702349a) that implemented the first pass.

**Comment by josephruscio** [comment]
So another metric that would be good to track is the number of dropped log lines i.e. log lines received for a bucket after it's TTL (#65) has expired.
