### ISSUE TITLE
Don't convert float values to strings for Librato reporter

### ISSUE THREAD

**Issue by mheffner** [ryansmith3136/l2met#63]
Librato API can accept float values as flat floats and doesn't require the string conversion in the payload.

**Comment by drio** [comment]
@ryandotsmith 
What do you think about [this](https://github.com/drio/l2met/commit/31e66ea0d524de3ec655feb474959f7f748e7dbe)  to address this ticket?

It you are fine with it I can also clean ff() and fi() since they won't be used.

**Comment by ryansmith3136** [comment]
@drio Looking good. Care to open a PR?
