### ISSUE TITLE
Librato outlet: Drop user email and token from payload

### ISSUE THREAD

**Issue by mheffner** [ryansmith3136/l2met#64]
The Librato API doesn't require the user and pass to be in the measurement payload. 

Convert:

``` go
type Payload struct {
    Name   string             `json:"name"`
    Time   int64              `json:"measure_time"`
    Val    string             `json:"value,omitempty"`
    Source string             `json:"source,omitempty"`
    User   string             `json:",omitempty"`
    Pass   string             `json:",omitempty"`
    Attr   *LibratoAttributes `json:"attributes,omitempty"`
}
```

to this:

``` go
type Payload struct {
    Name   string             `json:"name"`
    Time   int64              `json:"measure_time"`
    Val    string             `json:"value,omitempty"`
    Source string             `json:"source,omitempty"`
    Attr   *LibratoAttributes `json:"attributes,omitempty"`
}
```

**Comment by ryansmith3136** [comment]
I am pretty sure that by adding the `json:",omitempty"` tag to the struct field, json encoding will skip this field thus removing it from the json document that is submitted to librato.

It should also be noted that to achieve multi-tenancy, we [use the payload.User & payload.Pass fields](https://github.com/ryandotsmith/l2met/blob/master/outlet/librato_outlet.go#L145) in the code to ensure that we are grouping measurements correctly before submitting the measurements to Librato.

**Comment by ryansmith3136** [comment]
While we are on the subject, one thing that would make l2met's job simpler would be for librato to accept User & Password in the payload. This would allow me to remove all of my code that is responsible for grouping measurements with the correct account. What do you think about that?

**Comment by mheffner** [comment]
@ryandotsmith Well, the reason I submitted this was that I saw User and Pass fields in the payloads on our side. Maybe there's something else going on?

This is a sample measurement:

```
{"name":"railgun.default.load_avg_fifteen.mean","measure_time":1368654180,"value":"<val>","source":"<va>","User":"<email>","Pass":"<token>","attributes":{"display_min":0,"display_units_long":"u"}}
```

(actual values hidden with <>)

**Comment by mheffner** [comment]
@ryandotsmith So you mean a single payload would contain measurements for multiple different accounts?

**Comment by ryansmith3136** [comment]
> So you mean a single payload would contain measurements for multiple different accounts?

Yes.

**Comment by ryansmith3136** [comment]
> something else going on?

The other thing that is going on is my inability to Go. I need to pass a `-` as the struct field tag in order for the field to be properly omitted.
