### ISSUE TITLE
Make bucket TTLs configurable

### ISSUE THREAD

**Issue by josephruscio** [ryansmith3136/l2met#65]
`l2met` currently uses a hardcoded TTL of 3 minutes on buckets, meaning a bucket may be flushed up to 3 (or 2?) times at T=60,120,180 (T is in seconds) when the bucket represents the interval of 0-59.

Make this TTL configurable (suggest it take a number of seconds) and support a value equal to the flush interval, which would configure `l2met` to completely drop late messages and never report the same interval more than once. /cc @mheffner

**Comment by ryansmith3136** [comment]
I think this is completely reasonable. But only if we have good visibility into how many messages are being dropped as a result. I think @josephruscio mentioned the dropped visibility in #62

**Comment by ryansmith3136** [comment]
@josephruscio I am closing this issue in favor of #67 which separates the problem from a particular solution.
