### ISSUE TITLE
Support non-timer metrics

### ISSUE THREAD

**Issue by josephruscio** [ryansmith3136/l2met#69]
Currently l2met uniformly treats all metrics as _timers_ i.e. metrics comprised of a high number of individual measurements per interval that require statistical aggregation before reporting them upstream to something like Librato. For example the latency of servicing a web request would be measured thousands (or more!) times per interval on a heavily trafficked service. As such l2met generates 9 summary metrics (e.g. sum, mean, etc) for every metric.

Unfortunately this renders l2met extremely inefficient for metrics sampled and summarized somewhere else before being flushed into l2met on the desired reporting interval. In this case the user merely wishes to use l2met as a transport mechanism to report already computed summary statistics through logs. Example being the metrics reported by Heroku Postgres or AWS Cloudwatch.

Ideally there would be someway to indicate to l2met whether or not a given metric should have summary statistics calculated on it's measurements, or if they should merely be passed along with _last_ behavior i.e. always flush the last value reported in the interval.

/cc @mheffner @drio @mikehale @nextmat

**Comment by ryansmith3136** [comment]
I wonder if we need to update our logging conventions to support this. What if we could do something like this:

```
measure.db.latency=1ms sample.db.size=100MB
```

Which would translate to:

~~db.latency -> [min, p50, p95, p99, max, mean, sum, count]~~
~~db.size -> [last, sum, count]~~

```
db.latency -> [min, p50, p95, p99, max, mean, sum, count]
db.size -> [last]
```

**Comment by nextmat** [comment]
I was actually going to suggest something like that. That convention would also cover the common incremental counter use case.

**Comment by mikehale** [comment]
I like the idea of a `sample` prefix, however I don't understand why sum and count numbers would be emitted from l2met. @ryandotsmith can you explain why those are needed?

**Comment by mikehale** [comment]
Related issues: #14, #15.

**Comment by ryansmith3136** [comment]
@mikehale The more I have thought about my use case the more I realize that I don't even have a use case. Thanks for pointing that out.

**Comment by josephruscio** [comment]
@ryandotsmith I was going to :+1: @mikehale's comment. The "sample" mode should turn l2met into a transport-only mode, unless there's a use-case I'm not aware of.

**Comment by ryansmith3136** [comment]
Cool. Well I think I have a good enough understanding of the problem to start putting a PR together.

**Comment by josephruscio** [comment]
@ryandotsmith I'd also strongly suggest finding someway to remove the ambiguity of the `sample` prefix e.g. using some delimiting character not permitted in a metric name:

```
measure.db.latency=1ms sample#db.size=100MB
```

or

```
measure.db.latency=1ms db.size#sample=100MB
```

In the original example there will be no way to distinguish `sample.foo` (a metric named `foo` reported as a sample) from `sample.foo` (a metric named `sample.foo`).

**Comment by ryansmith3136** [comment]
@josephruscio Do you really think this is a problem? I haven't talked with anyone who was tripped up by not being able to use measure as a metrics name. I expect the same outcome if sample were a reserved word.

**Comment by ryansmith3136** [comment]
To be clear, my motivation is to keep the conventions as simple and consistent as possible. An alternitive to your first proposition could be:

```
measure#db.latency=1ms sample#db.size=100MB
```

Also, can you provide any data here? How many librato metrics have the name sample in them?

**Comment by josephruscio** [comment]
@ryandotsmith /cc @mheffner our experience with the millions of metric names our users have created is that pretty much any permutation will be used. From our production database:

```
mysql> SELECT COUNT(*) FROM metrics WHERE name LIKE "sample.%";
+----------+
| COUNT(*) |
+----------+
|      236 |
+----------+
```

and just for kicks:

```
mysql> SELECT COUNT(*) FROM metrics WHERE name LIKE "measure.%";
+----------+
| COUNT(*) |
+----------+
|       18 |
+----------+
```

**Comment by josephruscio** [comment]
> To be clear, my motivation is to keep the conventions as simple and consistent as possible. An alternitive to your first proposition could be:
> 
> measure#db.latency=1ms sample#db.size=100MB

I think this proposal is even better, I hadn't quite grasped that `measure` is also a reserved word.

**Comment by nextmat** [comment]
If we're going to expand the conventions it would be nice to have one as well which covers the simple counter case. While you can of course take a current `measure` and just ignore all the bits you don't care about, its a lot of unneeded context and having some type to push along the stack would be very useful for reasonable defaults. What about:

```
measure#db.latency=1ms sample#db.size=100MB count#db.queries=2
```

**Comment by josephruscio** [comment]
@nextmat to clarify would `count#` indicate that the value is an _increment_?

**Comment by nextmat** [comment]
I think if `count#` sent `sum` and `count` it could represent any kind of counter, but I would probably consider tying it to an incremental counter gauge preset in the Librato outlet later if we supported that.

**Comment by ryansmith3136** [comment]
All of this talk has led me to believe that we should not be afraid to abandoned the `measure.` convention and choose something that is more explicit.

```
time#db.latency=4ms 
-> [min, p50, p95, p99, max, mean, sum, count]
sample#db.size=10MB 
-> [last]
count#db.snapshots=2 
-> [sum]
```

**Comment by nextmat** [comment]
That looks good to me except I'd consider keeping `measure` instead of `time` because there are things you want the full set for that aren't timings. For example, queries, requests, etc.

**Comment by ryansmith3136** [comment]
@nextmat what do you mean by queries and requests? Wouldn't you be measuring the time it takes to make a request or a query?

**Comment by josephruscio** [comment]
@nextmat I'd tend to agree with @ryandotsmith's line of questioning, outside of time/rate/counts is there another [fundamental class of measurement](https://speakerdeck.com/monitorama/boston-2013-keynote-dr-neil-j-gunther?slide=7)?

OTOH though, are there cases where when tracking a _count_, the number of increments is large enough to make tracking distributions interesting? E.g. if on every POST to the Librato API we incremented a number of measurements, we'd want to know the total number of measurements being consumed, as well as p0, p50, p100 at least.

So it seems that we need to first differentiate between measurements that are a) for cut-through transport only and b) measurements that require summary statistics. We might also want to consider if there's an elegant way to differentiate on b) whether just simple summary stats are reported (count, sum, min, max) or if percentiles are included as well.

**Comment by ryansmith3136** [comment]
:8ball:  @josephruscio just referenced Dr. Neil J. Gunther.

**Comment by mheffner** [comment]
Timings are a specialized, but common, form for generic sampling. For example, I may want to measure the byte size for each incoming request and get the same sample statistics I would get measuring the time of the requests.

So, I would agree with @nextmat that calling these sampling statistics "timings" is a misnomer. See similar discussion for statsd: https://github.com/etsy/statsd/issues/98.

**Comment by josephruscio** [comment]
@mheffner ah I see now, I misunderstood what @nextmat was saying. Pretty sure I advocated for that too with the POST example, making my response doubly obtuse ;-). In the Etsy thread it looks like you advocated for still having a `timing` type given how common that use case is, even if it was just an alias for the more generic type. Do you think that would make sense here?

**Comment by mheffner** [comment]
@josephruscio I think timing makes sense to keep at an instrumentation library level given the common use case of measuring the time of code blocks. For statsd there's a tight coupling between client library and daemon, so there I think it would be harder to drop timing support now.

Given that this is green-field development, for a metrics transport system such as l2met I think sticking to a single fundamental metric type for this is best. Just _measure_ would work.

**Comment by craigkerstiens** [comment]
Adding myself @craigkerstiens and @gregburek to track for resolution of this.

**Comment by ryansmith3136** [comment]
@craigkerstiens One thing that is worth pointing out is that some of the [Heroku postgres metric logs](https://devcenter.heroku.com/articles/heroku-postgres-metrics-logs_) fall into the `sample` category.

**Comment by josephruscio** [comment]
Adding @runesoerensen to the thread to ensure compatibility in any implementation [AppHarbor](https://appharbor.com/) might be interested in.

**Comment by nextmat** [comment]
Fundamentally in agreement with @mheffner. I think this is mostly a vocabulary issue, to me timings are just a subset of sampling with a certain class of units associated. I don't think it makes sense to separate them out at the l2met level, personally. 

I tend to think of the `measure` case as sampling anything, while the `count` I was proposing is specifically a simplified case for just a count. The reason I originally proposed it send `sum` and `count` is that would allow you to get either average across members or total across members behavior with the most trivial payload, but I can see the argument for making it `count` only. 

Not sure I have a strong opinion either way - question being, are there cases where you want the average but you don't want the overhead of a full set of sampling metrics? For the sum case this is quite common, the average is less so.

**Comment by josephruscio** [comment]
@nextmat I'm inclined to think that it's only the sum. As soon as the average is involved you are characterizing the distribution to some extent, so we should either do that completely or not at all.

**Comment by ryansmith3136** [comment]
It seems that the conversation has led us to believe that the following proposed convention might be the next best move for l2met.

```
measure#db.latency=4ms 
-> [min, p50, p95, p99, max, mean, sum, count]
sample#db.size=10MB 
-> [last]
count#db.snapshots=2 
-> [sum]
```

**Comment by nextmat** [comment]
:+1: looks good to me

**Comment by gregburek** [comment]
This makes sense + :8ball:

**Comment by mathieuravaux** [comment]
:+1:

**Comment by danp** [comment]
:+1:

**Comment by josephruscio** [comment]
:+1:

Now that the fundamentals seem to be in order, _bike shed_ time :-) ... `min/max` or `p0/p100`?

**Comment by ryansmith3136** [comment]
@josephruscio I like p0/p100 because it brings more consistency to the protocol.

**Comment by danp** [comment]
I too like the p0/p100 bike shed color.

**Comment by josephruscio** [comment]
I guess it depends on how mathematically pure we want to be. I've seen min/max described that way before and it makes intuitive sense to me ... but some googling around shows some amount of disagreement e.g. whether the min is `p0` or in the 1st percentile. There's certainly no other value in the distribution that could be `p0`.

**Comment by ryansmith3136** [comment]
@josephruscio good point. If we use p0 and p100 that implies that there are 101 percentiles.

**Comment by nextmat** [comment]
I'd favor `min/max` as it seems both more explicit and less debatable.

**Comment by mheffner** [comment]
There's also a difference between the single values `min` and `max` and the distribution _pN_ of a sample set which itself has a minimum, maximum, sum, count.

**Comment by ryansmith3136** [comment]
This has been merged into master. Next, I will go on a doc updating crusade.

**Comment by ryansmith3136** [comment]
The [Usage article](https://github.com/ryandotsmith/l2met/wiki/Usage#logging-convention) in the wiki has been updated. I also [alluded](https://github.com/ryandotsmith/l2met/wiki/Usage#legacy-logging-convention) to the fact that we are supporting the `measure.` convention as a legacy convention until 3.X.X.

**Comment by BRMatt** [comment]
Do you happen to know if the postgres instrumentation logging heroku does will change to match these new conventions? On the one hand it seems a waste to store all the `measure#` metrics for things like db size etc., but on the other I guess you can't just abruptly change that sort of stuff. Would it be possible to have a labs app feature that uses the newer convention?

**Comment by gregburek** [comment]
@BRMatt I'm part of the Heroku Postgres team. 

As this change is released and brought into our l2met infra, we will be changing to `sample#` as the postgres measurements are being taken about once per minute. The exact migration path is still under discussion, but we have been pushing for these changes in order for this to happen. 

As for using a labs app feature, we are an addon provider and do not have access to the labs flag. We'll be considering other mechanisms to ease the transition.

**Comment by ryansmith3136** [comment]
@gregburek Thanks for the insight!

@BRMatt As you may have noticed, l2met will still support the `measure.` convention for quite some time. I know that quite a few people have used l2met for their visibility systems and I don't want to leave them out in the cold on this one. However, I hope that the new conventions are useful to the point that people will upgrade their logging statements. One of the advantages of building your metrics around logs is that they _should_ be super easy to change.

**Comment by BRMatt** [comment]
@gregburek Brilliant, thanks for the explanation.

@ryandotsmith Agreed, it's helpful this change doesn't conflict with the previous conventions.
