### ISSUE TITLE
Support librato's "source" measurement parameter

### ISSUE THREAD

**Issue by nzoschke** [ryansmith3136/l2met#7]
I would like to leverage Librato's dashboard templates:

http://support.metrics.librato.com/knowledgebase/articles/96653-instrument-and-dashboard-templates

The reasonable format for log messages would be:

```
source="git_push" measure="time" value="10.21"
source="http_curl" measure="time" value="0.02"
```

**Comment by gorsuch** [comment]
We want this as well - it would be a HUGE win.  HUGE I tell you.  This would potentially allow us to start shipping our collectd (lower-level system stats) metrics to librato without a terrible amount of work and allow us to leverage dashboards similar to how Noah describes.

**Comment by mikehale** [comment]
+1000

**Comment by ryansmith3136** [comment]
Message received. I am thinking of adding the following key: `lm_source`. The value for this key will be integrated into the metric that is sent to librato.

**Comment by sclasen** [comment]
+1

**Comment by nzoschke** [comment]
We talked about this in person, but why `lm_source` and not just `source` ?

**Comment by mikehale** [comment]
Does lm_source mean 'librato metric source'? Are you thinking there may be other types of sources?

**Comment by ryansmith3136** [comment]
This is now in production. I ended up using the source key. 

```
measure="time" source="git" val=42
```

**Comment by mikehale** [comment]
Awesome. Going to try to experiment with this some today.

**Comment by ryansmith3136** [comment]
done.
