### ISSUE TITLE
Support source as a parameter on drain URIs

### ISSUE THREAD

**Issue by josephruscio** [ryansmith3136/l2met#71]
Should support source prefix and metric prefix separately as parameters. E.g. if a user has a single Librato account in which they're monitoring multiple Heroku application instances, they'd prefer to have a single router or postgres dashboard that they can toggle from application to application.

**Comment by ryansmith3136** [comment]
Please help me understand something... How does the prefix parameter not solve for this problem?

**Comment by josephruscio** [comment]
AFAIK the `prefix` parameter pre-pends the metric name with the prefix and _not_ the source name, correct?

**Comment by ryansmith3136** [comment]
I see. So from Librato's perspective, you receive a piece of data with attributes **name** and **source**. Currently, you can set a prefix parameter for the **name** attribute, but you would rather that this go in the **source** attribute?

**Comment by nextmat** [comment]
@ryandotsmith Ideally I think we want to be able to configure for both cases independently.

**Comment by josephruscio** [comment]
@ryandotsmith as best I can tell, most people seem to be using prefix to differentiate between multiple applications on Heroku that all publish the same set of metrics roughly. This is best modelled in @librato by changing the source name, that a single set of template dashboards can be shared across multiple application instances. Per @nextmat's comment, there may still be some use-cases where prefixing the metric name is desirable, so supporting both would be nice.

Additionally think that in the case of a _source prefix_, it would still be passed along as a prefix to the empty string if no source was specified in the log lines. I think this will be the most common usage.

**Comment by ryansmith3136** [comment]
I see. I suppose you are right. Should be a simple enough change.

**Comment by softwaregravy** [comment]
+1
