### ISSUE TITLE
Increase flush to librato flush interval

### ISSUE THREAD

**Issue by mikehale** [ryansmith3136/l2met#8]
Currently all metrics are delayed by 60 seconds before being written to librato. Does it make sense to increase the flush interval to say 30 seconds? The last 60 seconds of data could still be used to make calculations in all cases except for brand new metrics.

**Comment by josephruscio** [comment]
We do support up to 1s resolution, and "raw data" is available through the API (and by extension graphs/dashboards) as soon as it hits the persistence layer. So if you have higher frequency data e.g. 5s or 10s, it could be accessed sooner.

**Comment by ryansmith3136** [comment]
The challenge with flushing data in short intervals is that we currently aggregate all metrics by the minute. Thus, if we flush minute=0 at minute=0 second=10, we only have 1/6th of our data set. This will mean that all charts will have a falling-off-the-cliff effect. We could mitigate this by aggregating by the second, or do some sort of moving buckets where the previous bucket impacts the current bucket.

**Comment by ryansmith3136** [comment]
Not sure there is any actionable item for this now. If it is a showstopper for your l2met usage, let me know and we can revisit.

**Comment by mikehale** [comment]
@ryandotsmith I think what I'm wanting here is something like what m2met provides. A simple pass-thru mode that receives specially annotated metrics on the log stream, formats them and sends them directly to librato without any aggregation. See #11.
