### ISSUE TITLE
Provide a convention for overriding measure time

### ISSUE THREAD

**Issue by mikehale** [ryansmith3136/l2met#9]
It looks like the only way to affect measure time is by setting the time in the syslog message received by l2met. https://github.com/ryandotsmith/l2met/blob/master/lib/l2met/receiver.rb#L71 In some cases (cloudwatch) the measure time is provided by an external source and should not be set automatically by logplex. It would be convenient to prefer a measure_time key over the time on the syslog message.

**Comment by ryansmith3136** [comment]
duplicated #15

**Comment by mikehale** [comment]
Thanks. Sorry for the dup.
