### ISSUE TITLE
Allow router source to be manually specified/include summation metric

### ISSUE THREAD

**Issue by BRMatt** [ryansmith3136/l2met#96]
Each of our users has their own subdomain in our multitenant app, and each router metric creates a source for each of these domains. While it's nice to be able to compare traffic between different sites, having a large number of sources for each metric prevents us from getting a single overview metric which we can evaluate/act on.

It'd be handy to have a separate source that amalgamates all of the router measurements. As it's useful to have stats for individual sites, it probably isn't necessary to stop l2met creating extra sources per domain. Maybe make it a configuration flag to help keep costs down? All it needs is for someone to send 1 request per minute to a few thousand subdomains and you'll have racked up a fair bill.

**Comment by ryansmith3136** [comment]
Great issue. Allow me to disclose that I hadn't really thought of the ramifications of per-domain sourcing on router metrics. I would definitely be up for picking something that is more reasonable.

**Comment by ryansmith3136** [comment]
If we wanted to remove this "feature", we could do so by removing this [line](https://github.com/ryandotsmith/l2met/blob/master/parser/log_data.go#L42-46). I am not sure how many people depend on this. I suspect it is mostly annoying.

**Comment by BRMatt** [comment]
It's useful if you want to see which site is producing the most traffic, but if we were to allow the specification of source in log lines it'd be trivial to write a small app specific metric that'd recreate the feature with safe guards(e.g. only log for sites that exist).

**Comment by ryansmith3136** [comment]
Are you aware that you can specify the source in the log lines? Checkout the [wiki](https://github.com/ryandotsmith/l2met/wiki/Usage#source) for the details.

**Comment by BRMatt** [comment]
Whoops, no I must've missed that! In that case this should definitely be
removed

**Comment by aseemk** [comment]
Hey guys, I just came across this, after I'd _just_ asked @josephruscio about this. We miss seeing the hostname as part of the source in our router metrics.

Our use case is that we serve both an HTML website and a JSON API from the same Heroku app (using vhosting), and it'd be great to differentiate stats between the two.

I'd appreciate if this could be reconsidered, as something that could be configurable. (Ideally, via the query string rather than a server config, so we could continue to use Librato's hosted l2met service.)

**Comment by aseemk** [comment]
Addendum: after reading https://github.com/ryandotsmith/l2met/issues/107#issuecomment-22908928 ("We should modify the Heroku router to read [`dyno=web.X`] and use it as the source"), I'm no longer sure how the host could/would get incorporated into the source. Tricky.
